// ============================================
// ARQUIVO: lib/contratiposData.ts
// O QUE FAZ: dados dos contratipos brasileiros — In The Box, JA Essence, Maison Viegas, Azza Parfum
// QUANDO MANDAR PRA IA: quando quiser adicionar marcas ou perfumes
// DEPENDE DE: nada
// ============================================

export interface PerfumeContratipo {
  id: string
  nome: string
  marca: string
  tipo: "EDP" | "EDT" | "EDC" | "Extrait"
  genero: "Masculino" | "Feminino" | "Unissex"
  inspiradoEm: string
  marcaOriginal: string
  familia: string
  notas: string[]
  preco_brl: number
  categoria: "contratipo"
}

export const CONTRATIPOS: PerfumeContratipo[] = [
  // ── IN THE BOX ─────────────────────────────────────────────────────────────
  {
    id: "itb-sauvage",
    nome: "Sauvagem",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Sauvage",
    marcaOriginal: "Dior",
    familia: "Aromático Fougère",
    notas: ["bergamota", "pimenta", "ambroxan", "cedro"],
    preco_brl: 149,
    categoria: "contratipo",
  },
  {
    id: "itb-aventus",
    nome: "Aventura",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Aventus",
    marcaOriginal: "Creed",
    familia: "Chypre Frutado",
    notas: ["abacaxi", "bétula", "almíscar", "patchouli"],
    preco_brl: 179,
    categoria: "contratipo",
  },
  {
    id: "itb-bleu-chanel",
    nome: "Bleu Intense",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Bleu de Chanel",
    marcaOriginal: "Chanel",
    familia: "Aromático Madeiroso",
    notas: ["citrus", "gengibre", "cedro", "sândalo"],
    preco_brl: 139,
    categoria: "contratipo",
  },
  {
    id: "itb-oud-wood",
    nome: "Oud Noir",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Oud Wood",
    marcaOriginal: "Tom Ford",
    familia: "Oriental Madeiroso",
    notas: ["oud", "sândalo", "baunilha", "pimenta rosa"],
    preco_brl: 189,
    categoria: "contratipo",
  },
  {
    id: "itb-la-vie-est-belle",
    nome: "La Belle Vie",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "La Vie Est Belle",
    marcaOriginal: "Lancôme",
    familia: "Oriental Floral",
    notas: ["iris", "pralinê", "baunilha", "patchouli"],
    preco_brl: 139,
    categoria: "contratipo",
  },
  {
    id: "itb-good-girl",
    nome: "Good Night",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Good Girl",
    marcaOriginal: "Carolina Herrera",
    familia: "Oriental Floral",
    notas: ["tuberosa", "jasmim", "cacau", "tonka"],
    preco_brl: 149,
    categoria: "contratipo",
  },
  {
    id: "itb-black-opium",
    nome: "Dark Opium",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Black Opium",
    marcaOriginal: "Yves Saint Laurent",
    familia: "Oriental Gourmand",
    notas: ["café", "baunilha", "flor de laranjeira", "cedro"],
    preco_brl: 149,
    categoria: "contratipo",
  },
  {
    id: "itb-acqua-di-gio",
    nome: "Acqua Fresca",
    marca: "In The Box",
    tipo: "EDT",
    genero: "Masculino",
    inspiradoEm: "Acqua di Giò",
    marcaOriginal: "Giorgio Armani",
    familia: "Aromático Aquático",
    notas: ["bergamota", "jasmim", "patchouli", "almíscar"],
    preco_brl: 119,
    categoria: "contratipo",
  },
  {
    id: "itb-coco-mademoiselle",
    nome: "Mademoiselle Rose",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Coco Mademoiselle",
    marcaOriginal: "Chanel",
    familia: "Oriental Floral",
    notas: ["rosa", "patchouli", "vetiver", "almíscar"],
    preco_brl: 159,
    categoria: "contratipo",
  },
  {
    id: "itb-santal-33",
    nome: "Sandalwood 33",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Santal 33",
    marcaOriginal: "Le Labo",
    familia: "Madeiroso Aromático",
    notas: ["sândalo", "couro", "cardamomo", "íris"],
    preco_brl: 169,
    categoria: "contratipo",
  },
  {
    id: "itb-1-million",
    nome: "Million Gold",
    marca: "In The Box",
    tipo: "EDT",
    genero: "Masculino",
    inspiradoEm: "1 Million",
    marcaOriginal: "Paco Rabanne",
    familia: "Oriental Especiado",
    notas: ["toranja", "hortelã", "canela", "couro"],
    preco_brl: 129,
    categoria: "contratipo",
  },
  {
    id: "itb-chance-chanel",
    nome: "Chance Dorée",
    marca: "In The Box",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Chance Eau Tendre",
    marcaOriginal: "Chanel",
    familia: "Floral Frutado",
    notas: ["toranja", "jasmim", "cédro", "almíscar branco"],
    preco_brl: 149,
    categoria: "contratipo",
  },

  // ── JA ESSENCE ─────────────────────────────────────────────────────────────
  {
    id: "ja-sauvage",
    nome: "Sauvage Essence",
    marca: "JA Essence",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Sauvage",
    marcaOriginal: "Dior",
    familia: "Aromático Fougère",
    notas: ["bergamota", "ambroxan", "pimenta rosa", "almíscar"],
    preco_brl: 89,
    categoria: "contratipo",
  },
  {
    id: "ja-aventus",
    nome: "Aventus JA",
    marca: "JA Essence",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Aventus",
    marcaOriginal: "Creed",
    familia: "Chypre Frutado",
    notas: ["abacaxi", "bétula", "almíscar", "âmbar"],
    preco_brl: 99,
    categoria: "contratipo",
  },
  {
    id: "ja-eros",
    nome: "Eros JA",
    marca: "JA Essence",
    tipo: "EDT",
    genero: "Masculino",
    inspiradoEm: "Eros",
    marcaOriginal: "Versace",
    familia: "Oriental Fougère",
    notas: ["hortelã", "maçã verde", "baunilha", "almíscar"],
    preco_brl: 79,
    categoria: "contratipo",
  },
  {
    id: "ja-212-men",
    nome: "Urban Man",
    marca: "JA Essence",
    tipo: "EDT",
    genero: "Masculino",
    inspiradoEm: "212 Men",
    marcaOriginal: "Carolina Herrera",
    familia: "Aromático Especiado",
    notas: ["bergamota", "cardamomo", "sândalo", "almíscar branco"],
    preco_brl: 79,
    categoria: "contratipo",
  },
  {
    id: "ja-good-girl",
    nome: "Good Girl JA",
    marca: "JA Essence",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Good Girl",
    marcaOriginal: "Carolina Herrera",
    familia: "Oriental Floral",
    notas: ["jasmim", "tuberosa", "almíscar", "baunilha"],
    preco_brl: 89,
    categoria: "contratipo",
  },
  {
    id: "ja-black-opium",
    nome: "Black Opium JA",
    marca: "JA Essence",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Black Opium",
    marcaOriginal: "Yves Saint Laurent",
    familia: "Oriental Gourmand",
    notas: ["café", "baunilha", "pera", "patchouli"],
    preco_brl: 89,
    categoria: "contratipo",
  },
  {
    id: "ja-la-vie-est-belle",
    nome: "Belle de Vie JA",
    marca: "JA Essence",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "La Vie Est Belle",
    marcaOriginal: "Lancôme",
    familia: "Oriental Floral",
    notas: ["iris", "pralinê", "baunilha", "âmbar"],
    preco_brl: 89,
    categoria: "contratipo",
  },
  {
    id: "ja-si",
    nome: "Si JA",
    marca: "JA Essence",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Si",
    marcaOriginal: "Giorgio Armani",
    familia: "Chypre Floral",
    notas: ["groselha negra", "rosa", "patchouli", "baunilha"],
    preco_brl: 89,
    categoria: "contratipo",
  },
  {
    id: "ja-coco-mademoiselle",
    nome: "Mademoiselle JA",
    marca: "JA Essence",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Coco Mademoiselle",
    marcaOriginal: "Chanel",
    familia: "Oriental Floral",
    notas: ["bergamota", "rosa", "patchouli", "vetiver"],
    preco_brl: 99,
    categoria: "contratipo",
  },
  {
    id: "ja-acqua-di-gio",
    nome: "Acqua JA",
    marca: "JA Essence",
    tipo: "EDT",
    genero: "Masculino",
    inspiradoEm: "Acqua di Giò",
    marcaOriginal: "Giorgio Armani",
    familia: "Aromático Aquático",
    notas: ["limão", "bergamota", "jasmim", "almíscar"],
    preco_brl: 69,
    categoria: "contratipo",
  },

  // ── MAISON VIEGAS ──────────────────────────────────────────────────────────
  {
    id: "mv-baccarat",
    nome: "Rouge 540 MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Baccarat Rouge 540",
    marcaOriginal: "Maison Francis Kurkdjian",
    familia: "Floral Amadeirado Almiscarado",
    notas: ["jasmim", "açafrão", "cedro", "ambroxan"],
    preco_brl: 219,
    categoria: "contratipo",
  },
  {
    id: "mv-oud-ispahan",
    nome: "Oud Ispahan MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Oud Ispahan",
    marcaOriginal: "Dior",
    familia: "Oriental Amadeirado",
    notas: ["oud", "rosa", "patchouli", "incenso"],
    preco_brl: 229,
    categoria: "contratipo",
  },
  {
    id: "mv-black-orchid",
    nome: "Orchidée Noire MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Black Orchid",
    marcaOriginal: "Tom Ford",
    familia: "Oriental Floral",
    notas: ["orquídea preta", "trufa", "baunilha", "patchouli"],
    preco_brl: 219,
    categoria: "contratipo",
  },
  {
    id: "mv-lost-cherry",
    nome: "Cerise Perdue MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Lost Cherry",
    marcaOriginal: "Tom Ford",
    familia: "Oriental Frutado",
    notas: ["cereja", "amêndoa", "alcaçuz", "baunilha"],
    preco_brl: 239,
    categoria: "contratipo",
  },
  {
    id: "mv-aventus",
    nome: "Aventus MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Aventus",
    marcaOriginal: "Creed",
    familia: "Chypre Frutado",
    notas: ["abacaxi", "bétula", "patchouli", "almíscar"],
    preco_brl: 249,
    categoria: "contratipo",
  },
  {
    id: "mv-coco-mademoiselle",
    nome: "Mademoiselle MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Coco Mademoiselle",
    marcaOriginal: "Chanel",
    familia: "Oriental Floral",
    notas: ["bergamota", "rosa de maio", "patchouli", "vetiver"],
    preco_brl: 219,
    categoria: "contratipo",
  },
  {
    id: "mv-tobacco-oud",
    nome: "Tabac & Oud MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Tobacco Oud",
    marcaOriginal: "Tom Ford",
    familia: "Oriental Amadeirado",
    notas: ["tabaco", "oud", "especiarias", "âmbar"],
    preco_brl: 229,
    categoria: "contratipo",
  },
  {
    id: "mv-si",
    nome: "Si Intense MV",
    marca: "Maison Viegas",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Si Intense",
    marcaOriginal: "Giorgio Armani",
    familia: "Chypre Floral",
    notas: ["groselha negra", "rosa", "patchouli", "almíscar"],
    preco_brl: 209,
    categoria: "contratipo",
  },

  // ── AZZA PARFUM ────────────────────────────────────────────────────────────
  {
    id: "az-baccarat",
    nome: "Baccarat Rouge AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Unissex",
    inspiradoEm: "Baccarat Rouge 540",
    marcaOriginal: "Maison Francis Kurkdjian",
    familia: "Floral Amadeirado Almiscarado",
    notas: ["jasmim", "açafrão", "cedro", "ambroxan"],
    preco_brl: 159,
    categoria: "contratipo",
  },
  {
    id: "az-sauvage",
    nome: "Sauvage AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Sauvage",
    marcaOriginal: "Dior",
    familia: "Aromático Fougère",
    notas: ["bergamota", "pimenta", "ambroxan", "cedro virgínia"],
    preco_brl: 139,
    categoria: "contratipo",
  },
  {
    id: "az-aventus",
    nome: "Aventus AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Aventus",
    marcaOriginal: "Creed",
    familia: "Chypre Frutado",
    notas: ["abacaxi", "bétula", "almíscar", "patchouli"],
    preco_brl: 149,
    categoria: "contratipo",
  },
  {
    id: "az-good-girl",
    nome: "Good Girl AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Good Girl",
    marcaOriginal: "Carolina Herrera",
    familia: "Oriental Floral",
    notas: ["tuberosa", "jasmim", "almíscar", "baunilha"],
    preco_brl: 139,
    categoria: "contratipo",
  },
  {
    id: "az-black-opium",
    nome: "Black Opium AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Black Opium",
    marcaOriginal: "Yves Saint Laurent",
    familia: "Oriental Gourmand",
    notas: ["café", "baunilha", "pêssego", "cedro"],
    preco_brl: 139,
    categoria: "contratipo",
  },
  {
    id: "az-eros",
    nome: "Eros AP",
    marca: "Azza Parfum",
    tipo: "EDT",
    genero: "Masculino",
    inspiradoEm: "Eros",
    marcaOriginal: "Versace",
    familia: "Oriental Fougère",
    notas: ["hortelã", "maçã verde", "baunilha", "cedro"],
    preco_brl: 119,
    categoria: "contratipo",
  },
  {
    id: "az-la-vie-est-belle",
    nome: "La Belle AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "La Vie Est Belle",
    marcaOriginal: "Lancôme",
    familia: "Oriental Floral",
    notas: ["iris", "pralinê", "baunilha", "âmbar"],
    preco_brl: 129,
    categoria: "contratipo",
  },
  {
    id: "az-bleu-chanel",
    nome: "Bleu AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Masculino",
    inspiradoEm: "Bleu de Chanel",
    marcaOriginal: "Chanel",
    familia: "Aromático Madeiroso",
    notas: ["citrus", "gengibre", "cedro", "sândalo"],
    preco_brl: 129,
    categoria: "contratipo",
  },
  {
    id: "az-mon-guerlain",
    nome: "Mon Amour AP",
    marca: "Azza Parfum",
    tipo: "EDP",
    genero: "Feminino",
    inspiradoEm: "Mon Guerlain",
    marcaOriginal: "Guerlain",
    familia: "Oriental Lavanda",
    notas: ["lavanda", "baunilha", "tonka", "almíscar"],
    preco_brl: 129,
    categoria: "contratipo",
  },
]

// ── Funções auxiliares ───────────────────────────────────────────────────────

export function buscarTodosContratipos(): PerfumeContratipo[] {
  return CONTRATIPOS
}

export function buscarContratiposPorMarca(marca: string): PerfumeContratipo[] {
  return CONTRATIPOS.filter((p) => p.marca.toLowerCase() === marca.toLowerCase())
}

export function buscarContratiposPorGenero(
  genero: "Masculino" | "Feminino" | "Unissex"
): PerfumeContratipo[] {
  return CONTRATIPOS.filter((p) => p.genero === genero)
}

export function buscarContratiposPorInspiracao(nome: string): PerfumeContratipo[] {
  const q = nome.toLowerCase()
  return CONTRATIPOS.filter(
    (p) =>
      p.inspiradoEm.toLowerCase().includes(q) ||
      p.marcaOriginal.toLowerCase().includes(q)
  )
}
